export const typeFormMyOrder = {
  commads_id: "",
  deliveryType_id: "",
  statusRequest_id: "",
  payment_id: "",
  coupon: "",
  note: "",
  address: "",
  number: "",
  neighborhood: "",
  city: "",
  uf: "",
  PointReferences: "",
  cash: "",
  timeDelivery: "",
  item: [
    {
      amount: "",
      product_id: "",
      price: "",
      note: "",
      additionItem: "",
    },
  ],
};
